### ISSUE TITLE
Can you split the PEM file and allow us to provide separate key and cert files?

### ISSUE THREAD

**Issue by amrabinowitz** [buzzm/WebF3#1]
Hi Buzz,
The LetsEncrypt client I use, certbot, supplies the private key and the full chain as two separate files. In order to use these with WebF we now need to run an extra script to combine the two files into one. It would be easier for us if we can specify the 2 files separately, thus avoiding having to create a new, protected file, containing a copy of the private key.
No hurry, it just seems like a nice feature if you have time.
Also, I was wondering if you had time to look at allowing us to add returned headers, specifically a Location: header to be used for redirecting browsers with a 3xx return code.
Thanks,
Ari

**Comment by buzzm** [comment]
I know this sounds a little vendorish but could we bundle the Top 3 mods into something I look at, say, every 4-6 weeks?

**Comment by amrabinowitz** [comment]
Sure, I’m not expecting rapid responses. I’m more concerned about Jennifer’s issue. Mine are just enhancement requests. 
Thanks,
Ari

**Comment by amrabinowitz** [comment]
This seems to be working now.
